name: ci
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  upload-metrics:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: upload coverage via cli
        run: |
          curl -Os https://cli.codecov.io/v0.8.0/linux/codecov
          chmod +x codecov
          sha="${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
          ./codecov --auto-load-params-from=GithubActions --codecov-yml-path .codecov.yml -v pr-base-picking --slug="${{ github.repository }}" --base-sha="${{ github.event.pull_request.base.sha }}" --service github -t ${{ secrets.CODECOV_TOKEN }}
          ./codecov --auto-load-params-from=GithubActions --codecov-yml-path .codecov.yml -v do-upload --slug="${{ github.repository }}" --sha="${sha}" -f torchscript_input_files_coverage.dat -F torchscript_input_files --git-service github -t ${{ secrets.CODECOV_TOKEN }} 
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: upload coverage via cli
        run: |
          curl -Os https://cli.codecov.io/v0.8.0/linux/codecov
          chmod +x codecov
          sha="${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
          ./codecov --auto-load-params-from=GithubActions --codecov-yml-path .codecov.yml -v pr-base-picking --slug="${{ github.repository }}" --base-sha="${{ github.event.pull_request.base.sha }}" --service github -t ${{ secrets.CODECOV_TOKEN }}
          ./codecov --auto-load-params-from=GithubActions --codecov-yml-path .codecov.yml -v do-upload --slug="${{ github.repository }}" --sha="${sha}" -f onboard_av_binary_coverage.dat -F onboard_av_binary --git-service github -t ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#           ./codecov --verbose upload-process --disable-search -n "onboard_av_binary"-${{ github.run_id }} --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -F onboard_av_binary -f onboard_av_binary_coverage.dat
# # --parent-sha de19c68b335e6e17e1e5b3204935d3c5e5d5b716
      # - uses: codecov/codecov-action@v4
      #   with:
      #     file: torchscript_input_files_coverage.dat
      #     flags: torchscript_input_files
      #     verbose: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     codecov_yml_path: .codecov.yml

      # - uses: codecov/codecov-action@v4
      #   with:
      #     file: onboard_av_binary_coverage.dat
      #     flags: onboard_av_binary
      #     verbose: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     codecov_yml_path: .codecov.yml

