name: ci
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  upload-metrics:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: codecov/codecov-action@v4
        with:
          file: torchscript_input_files_coverage.dat
          flags: torchscript_input_files
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: .codecov.yml

      - uses: codecov/codecov-action@v4
        with:
          file: onboard_av_binary_coverage.dat
          flags: onboard_av_binary
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: .codecov.yml
      
      - name: fetch codecov results
        run: |
          curl --request GET \
              --url "https://api.codecov.io/api/v2/github/Ryang20718/repos/cflag/report/tree?sha=${{ github.event.pull_request.head.sha }}" \
              --header "accept: application/json" \
              --header "authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}"

      - name: fetch codecov flag results
        run: |
          curl --request GET \
              --url "https://api.codecov.io/api/v2/github/Ryang20718/repos/cflag/report/tree?flag=onboard_av_binary&sha=${{ github.event.pull_request.head.sha }}" \
              --header "accept: application/json" \
              --header "authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}"

      - name: fetch codecov flag results
        run: |
          curl --request GET \
              --url "https://api.codecov.io/api/v2/github/Ryang20718/repos/cflag/report/tree?flag=torchscript_input_files&sha=${{ github.event.pull_request.head.sha }}" \
              --header "accept: application/json" \
              --header "authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}"
  codecov-results:
    runs-on: ubuntu-latest
    needs: [upload-metrics]
    steps:
      - name: Sleep for 1.5min
        run: sleep 100s
      - name: fetch codecov results
        run: |
          curl --request GET \
              --url "https://api.codecov.io/api/v2/github/Ryang20718/repos/cflag/report/tree?sha=${{ github.event.pull_request.head.sha }}" \
              --header "accept: application/json" \
              --header "authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}"

      - name: fetch codecov flag results
        run: |
          curl --request GET \
              --url "https://api.codecov.io/api/v2/github/Ryang20718/repos/cflag/report/tree?flag=onboard_av_binary&sha=${{ github.event.pull_request.head.sha }}" \
              --header "accept: application/json" \
              --header "authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}"

      - name: fetch codecov flag results
        run: |
          curl --request GET \
              --url "https://api.codecov.io/api/v2/github/Ryang20718/repos/cflag/report/tree?flag=torchscript_input_files&sha=${{ github.event.pull_request.head.sha }}" \
              --header "accept: application/json" \
              --header "authorization: Bearer ${{ secrets.CODECOV_API_TOKEN }}"
