name: ci
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  upload-metrics:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'codecov-bypass') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: codecov/codecov-action@v4
        with:
          file: torchscript_input_files_coverage.dat
          flags: torchscript_input_files
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: .codecov.yml

      - uses: codecov/codecov-action@v4
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'codecov-bypass') }} 
        with:
          file: onboard_av_binary_coverage.dat
          flags: onboard_av_binary
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: .codecov.yml

  coverage-bypass:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'codecov-bypass') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: upload empty report for status checks
        run: |
          curl -Os https://cli.codecov.io/v0.8.0/linux/codecov
          chmod +x codecov
          ./codecov -v create-commit -t ${{ secrets.CODECOV_TOKEN }} -C ${{ github.event.pull_request.head.sha }}
          ./codecov -v create-report -t ${{ secrets.CODECOV_TOKEN }} -C ${{ github.event.pull_request.head.sha }}
          ./codecov -v empty-upload -t ${{ secrets.CODECOV_TOKEN }} --force -C ${{ github.event.pull_request.head.sha }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}