name: ci
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  upload-metrics:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'codecov-bypass') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print labels
        run: |
          echo "${{ toJSON(github.event.pull_request.labels.*.name) }}"

      - run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          echo "$labels"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

      - uses: codecov/codecov-action@v4
        with:
          file: torchscript_input_files_coverage.dat
          flags: torchscript_input_files
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: .codecov.yml

      - uses: codecov/codecov-action@v4
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'codecov-bypass') }} 
        with:
          file: onboard_av_binary_coverage.dat
          flags: onboard_av_binary
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov_yml_path: .codecov.yml

  coverage-bypass:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pr Labels
        id: get-pr-labels
        run: |
          codecov_bypass="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels | map(select(.name == "codecov-bypass")) | length > 0')"
          echo "codecov_bypass=$codecov_bypass" >> $GITHUB_OUTPUT
          echo "codecov_bypass=$codecov_bypass"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

      - name: upload empty report for status checks
        if: ${{ steps.get-pr-labels.outputs.codecov_bypass == 'true' }}
        run: |
          curl -Os https://cli.codecov.io/v0.8.0/linux/codecov
          chmod +x codecov
          ./codecov -v create-commit -t ${{ secrets.CODECOV_TOKEN }} -C ${{ github.event.pull_request.head.sha }}
          ./codecov -v create-report -t ${{ secrets.CODECOV_TOKEN }} -C ${{ github.event.pull_request.head.sha }}
          ./codecov -v empty-upload -t ${{ secrets.CODECOV_TOKEN }} --force -C ${{ github.event.pull_request.head.sha }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}