name: Testing Merge
on:
  pull_request:
    types: [closed]

defaults:
  run:
    shell: bash

jobs:
debug-payload:
  runs-on: ubuntu-latest
  steps:
    - name: Print entire payload
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Full payload:"
        echo '${{ toJSON(github.event) }}' | jq '.'