name: Testing Merge
on:
  pull_request:
    types: [closed]

defaults:
  run:
    shell: bash

jobs:
  debug-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Print entire payload
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Full payload:"
          echo '${{ toJSON(github.event) }}' | jq '.'
      - name: Print head sha
        run: |
          echo "Event: ${{ github.event.pull_request.head.sha }}"
#
  get-squash-merge-sha:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the base branch (e.g., main)
      # 1. You start here, with the PR code checked out.
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # 2. Simulate the squash merge to get the final code state and a potential SHA.
      - name: Get Simulated Squash Commit
        id: get_sha
        run: |
          set -e # Exit immediately if a command fails
          # Define branch names from the GitHub context for clarity
          TARGET_BRANCH=${{ github.base_ref }}
          PR_BRANCH=${{ github.head_ref }}
          echo "Simulating squash merge of '$PR_BRANCH' into '$TARGET_BRANCH'..."
          # Fetch the target branch so we can switch to it
          git fetch origin $TARGET_BRANCH:$TARGET_BRANCH
          
          # Switch to the target branch
          git checkout $TARGET_BRANCH
          # Use merge --squash to apply the PR's changes to the target branch
          # This stages all the changes but does not commit them.
          git merge --squash $PR_BRANCH
          # Configure a git user to create the commit
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create the local commit to get its SHA
          git commit -m "Simulated squash of PR #${{ github.event.number }}"
          # Output the SHA of the new commit
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Display the Result
        run: echo "The simulated squash-merge SHA is ${{ steps.get_sha.outputs.sha }}"