name: Codecov PR Status Checks

# https://docs.github.com/en/webhooks/webhook-events-and-payloads#check_run
# This workflow is triggered for each 3rd party check run completion.
# in this workflow, we post a comment to the PR with useful guidance on how to navigate the failed check
on:
  check_run:
    types: [completed]

jobs:
  check_codecov:
    if: contains(github.event.check_run.name, 'codecov') && github.event.check_run.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Check Name: ${{ github.event.check_run.name }}"
          echo "Status: ${{ github.event.check_run.conclusion }}"
          echo "PR Number: ${{ github.event.check_run.check_suite.pull_requests[0].number }}"

      - name: Check if comment exists and add if missing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          COMMENT_BODY="
          Codecov status check has failed.

          <details>
            <summary>If you have not yet logged in to codecov</summary>
            Please do so via [here](test).
          </details>

          <details>
            <summary>If codecov project/patch status checks are failing, here are some tips to resolve those errors!</summary>
            Please ensure your changes are tested :smile.

            There are some known limitations with codecov documented
            [here](test).

            If you believe this is a false positive and none of the suggestions above help, please add the label "codecov-bypass" to the PR.

            For any additional features/concerns, please reach out to #tools-help on slack!
          </details>
          "
          PR_NUMBER=${{ github.event.check_run.check_suite.pull_requests[0].number }}
          REPO=${{ github.repository }}

          # Fetch existing comments
          COMMENTS=$(gh pr view $PR_NUMBER --repo $REPO --json comments --jq '.comments[].body')

          # Check if the comment already exists
          if echo "$COMMENTS" | grep -qF "$COMMENT_BODY"; then
            echo "Comment already exists, skipping."
          else
            echo "Adding comment to PR..."
            gh pr comment $PR_NUMBER --repo $REPO --body "$COMMENT_BODY"
          fi

  codecov_status_checks:
    if: contains(github.event.check_run.name, 'codecov')
    runs-on: ubuntu-latest
    steps:
      - name: Update Commit Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=${{ github.event.check_run.check_suite.pull_requests[0].head.sha }}
          PR_NUMBER=${{ github.event.check_run.check_suite.pull_requests[0].number }}
          CHECK_RUN_NAME=${{ github.event.check_run.name }}
          CONCLUSION=${{ github.event.check_run.conclusion }}

          echo "Check Run Name: $CHECK_RUN_NAME"
          echo "Commit SHA: $SHA"
          echo "Conclusion: $CONCLUSION"

          STATUS="pending"
          if [ "$CONCLUSION" == "success" ]; then
            STATUS="success"
          else; then
            STATUS="failure"
          fi

          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/statuses/$SHA \
               -d "{\"state\":\"$STATUS\", \"context\":\"CI Status\", \"description\":\"Check Run: $CHECK_RUN_NAME\", \"target_url\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
