name: Check Run Trigger

on:
  check_suite:
    types: [completed]

jobs:
  check_run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Check Name: ${{ github.event.check_suite.app.name }}"
          echo "PR Number: ${{ github.event.check_suite.pull_requests[0].number }}"
          echo "Status: ${{ github.event.check_suite.conclusion }}"
    
      - name: Print full event payload
        run: echo '${{ toJson(github.event) }}'