name: Check Run Trigger

on:
  check_run:
    types: [completed]

jobs:
  check_run_job:
    if: contains(github.event.check_run.name, 'codecov') && github.event.check_run.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Check Name: ${{ github.event.check_run.name }}"
          echo "Status: ${{ github.event.check_run.conclusion }}"
          echo "PR Number: ${{ github.event.check_suite.pull_requests[0].number }}"
    
      - name: Print full event payload
        run: echo '${{ toJson(github.event) }}'
