name: Check Run Trigger

on:
  check_run:
    types: [completed]

jobs:
  check_run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Check Name: ${{ github.event.check_run.name }}"
          echo "PR Number: ${{ github.event.check_run.url }}"
          echo "Status: ${{ github.event.check_run.conclusion }}"
    
      - name: Print full event payload
        run: echo '${{ toJson(github.event) }}'
#