name: ci
on:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: write
  actions: write
  # pull_requests: write
  pages: write
  id-token: write

jobs:
  cpu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install numpy
        run: |
          uv pip install --system numpy

      - name: Run import check
        run: |
          python3 -c "import time;import random; print(time.time()); time.sleep(random.randint(20, 100)); print(time.time())"
          exit 1

      - name: Cancel workflow on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run cancel ${{ github.run_id }}

  gpu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install numpy
        run: |
          uv pip install --system numpy

      - name: Run import check
        run: |
          python3 -c "import time;import random; print(time.time()); time.sleep(random.randint(20, 110)); print(time.time())"
          exit 1

      - name: Cancel workflow on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run cancel ${{ github.run_id }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 #

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install numpy
        run: |
          uv pip install --system numpy

      - name: Run import check
        run: |
          python3 -c "import time;import random; print(time.time()); time.sleep(random.randint(1, 60)); print(time.time())"
          exit 1

      - name: Cancel workflow on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run cancel ${{ github.run_id }}