name: ci
on:
  pull_request:

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        job: [build, cpu-test, gpu-test]
    name: ${{ matrix.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ${{ matrix.job }}
        uses: ./.github/actions/${{ matrix.job }}